# Generated by Django 2.2.5 on 2020-07-19 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('description', models.CharField(max_length=260)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 7, 19, 16, 27, 14, 513928, tzinfo=utc))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 7, 19, 16, 27, 14, 513928, tzinfo=utc))),
            ],
        ),
    ]
