# Generated by Django 3.0.8 on 2020-07-25 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc



class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='description',
            new_name='Parts_description',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='name',
            new_name='Parts_name',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='price',
            new_name='Parts_price',
        ),
        migrations.AlterField(
            model_name='parts',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 25, 8, 44, 44, 655410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parts',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 25, 8, 44, 44, 655410, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='parts',
            table='parts',
        ),
    ]
